### PR TITLE
Add new feature: MQTT topic temperature input sensor

### PR DESCRIPTION
**Pull request by Jean-Emile**
Add new feature: MQTT topic as input for an external temperature sensor 

[FIX] It turns out that the Relay of my board is connected to GPI05 not GPI012 as showed in the schematic.

### CODE REVIEW

**Comment by glynhudson** [comment]
Thanks a lot :+1:

**Comment by Jean-Emile** [comment]
Thanks!  I started to integrate several emonTH V2 to drive the thermostat relay but also do a more deep cleanup of the relay code source. 
 Do you think it possible to have a discount to buy extra emonTH sensors ? ;-) FYI, I gonna to share the update patchset.
Thanks,

**Comment by glynhudson** [comment]
Sure, I've emailed you a 20% discount code :-)

**Comment by kylix34** [comment]
Hi Jean-Emile! Which SDK version did you use to compile? Would it be possible to port this project to ESP32?
I also did some changes and it takes the temperature from the serial connection. Besides the temperature I get: humidity, RSSI, battery level of the remote node and the atmosferic pressure (I'm using a BME280 module on the remote node). All the sensor values were also added to the Thingspeak html page (https://community.openenergymonitor.org/t/wifi-1ch-relay-get-temperature-from-433mhz-remote-node/2406/6).
It would also be cool to have the OTA feature (I already tried but didn't manage to make it work: last version of esphttpd and 2.1.0 SDK version).

**Comment by Jean-Emile** [comment]
Hi kylix3,

I'm using the lastest SDK of Espressif (https://github.com/esp8266/esp8266-wiki/wiki/Toolchain). 

FYI, I started to rewrite/adapt the project with "ESP8266 core for Arduino" (https://github.com/esp8266/Arduino) to add new features more easily and reduce the amount of code to maintain.

After, this integration, IMHO, we can try http://esp8266.github.io/Arduino/versions/2.0.0/doc/ota_updates/ota_updates.html to have OTA.

Best regards,

**Comment by kylix34** [comment]
WOW ... great news!  I hope you'll make the code public.

**Comment by Jean-Emile** [comment]
Yes, I will.

**Comment by Jean-Emile** [comment]
I  pushed a new version of the firmware https://github.com/Jean-Emile/ESP8266_Thermostat
This is not yet usable, but i will continue to work on it depending on my free time.

**Comment by kylix34** [comment]
I'll try it as soon as possible. I like that you're using LowPower Lab's library for the RFM69 module.
I didn't see the Thingspeak.html page but I suppose I could add it later. Thanks!

**Comment by fluppie** [comment]
MQTT strSubsTopic: heating/control/relay/e, strTopic: /ESP_Easy_Mega_3/HTU21D_3/Temperature 
MQTT temp: 2200
MQTT topic: /ESP_Easy_Mega_3/HTU21D_3/Temperature, data: 22.61

I guess I get rounded values is because of this line?
_os_sprintf(temp,"%d.%d",(int)MQTTreading/100,MQTTreading-((int)MQTTreading/100)*100);_

**Comment by Jean-Emile** [comment]
I don't think so, however, there is a bug in my pull request in line
user_main.c#L202
"MQTTreading=atoi(strData)*100;" have to be replace by "MQTTreading=atoi
(strData)"

Best regards,

JeD

**Comment by fluppie** [comment]
```
//			MQTTreading=atoi(strData);
			MQTTreading=atoi(strData)*100;

//				os_sprintf(temp,"%d.%d",(int)MQTTreading/1,MQTTreading-((int)MQTTreading/1)*1);
				os_sprintf(temp,"%d.%d",(int)MQTTreading/100,MQTTreading-((int)MQTTreading/100)*100);
```

MQTTtemp 21
Visually in thermostat.html 0.2 °C

MQTT strSubsTopic: heating/control/relay/e, strTopic: /ESP_Easy_Mega_3/HTU21D_3/Temperature 

MQTT temp: 21 

MQTT topic: /ESP_Easy_Mega_3/HTU21D_3/Temperature, data: 21.88 





```
			MQTTreading=atoi(strData);
//			MQTTreading=atoi(strData)*100;

				os_sprintf(temp,"%d.%d",(int)MQTTreading/1,MQTTreading-((int)MQTTreading/1)*1);
//				os_sprintf(temp,"%d.%d",(int)MQTTreading/100,MQTTreading-((int)MQTTreading/100)*100);

```
MQTTtemp 21
Visually in thermostat.html 21.0 °C

MQTT strSubsTopic: heating/control/relay/e, strTopic: /ESP_Easy_Mega_3/HTU21D_3/Temperature 

MQTT temp: 21 

MQTT topic: /ESP_Easy_Mega_3/HTU21D_3/Temperature, data: 21.85

I think a Integer/Long string formatting issue?

**Comment by fluppie** [comment]
And another "combo"

MQTT strSubsTopic: heating/control/relay/e, strTopic: /ESP_Easy_Mega_3/HTU21D_3/Temperature 
MQTT temp: 2100 
MQTT topic: /ESP_Easy_Mega_3/HTU21D_3/Temperature, data: 21.80

MQTTtemp 2100
Visually in thermostat.html 2100.0 °C

```
//		MQTTreading=atoi(strData);
		MQTTreading=atoi(strData)*100;

				os_sprintf(temp,"%d.%d",(int)MQTTreading/1,MQTTreading-((int)MQTTreading/1)*1);
//				os_sprintf(temp,"%d.%d",(int)MQTTreading/100,MQTTreading-((int)MQTTreading/100)*100);
```

**Comment by Jean-Emile** [comment]
It seems that you are publishing a float, you should do
MQTTreading=atof(strData)*100;

**Comment by fluppie** [comment]
For me that doesn't work as I use SDK 1.3.0 on my Windows system (https://github.com/CHERTS/esp8266-devkit)

```
c:/espressif/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/5.2.0/../../../../xtensa-lx106-elf/bin/ld.exe: build/app.out section `.text' will not fit in region `iram1_0_seg'
c:/espressif/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/5.2.0/../../../../xtensa-lx106-elf/lib\libc.a(lib_a-mallocr.o):(.literal+0x20): undefined reference to `_sbrk_r'
c:/espressif/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/5.2.0/../../../../xtensa-lx106-elf/lib\libc.a(lib_a-mallocr.o): In function `malloc_extend_top':
d:\Neo\crosstool\dl\newlib-2.0.0\build\xtensa-lx106-elf\newlib\libc\stdlib/../../../../../newlib/libc/stdlib/mallocr.c:2165: undefined reference to `_sbrk_r'
d:\Neo\crosstool\dl\newlib-2.0.0\build\xtensa-lx106-elf\newlib\libc\stdlib/../../../../../newlib/libc/stdlib/mallocr.c:2202: undefined reference to `_sbrk_r'
c:/espressif/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/5.2.0/../../../../xtensa-lx106-elf/lib\libc.a(lib_a-freer.o): In function `_malloc_trim_r':
d:\Neo\crosstool\dl\newlib-2.0.0\build\xtensa-lx106-elf\newlib\libc\stdlib/../../../../../newlib/libc/stdlib/mallocr.c:3325: undefined reference to `_sbrk_r'
d:\Neo\crosstool\dl\newlib-2.0.0\build\xtensa-lx106-elf\newlib\libc\stdlib/../../../../../newlib/libc/stdlib/mallocr.c:3332: undefined reference to `_sbrk_r'
c:/espressif/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/5.2.0/../../../../xtensa-lx106-elf/lib\libc.a(lib_a-freer.o):d:\Neo\crosstool\dl\newlib-2.0.0\build\xtensa-lx106-elf\newlib\libc\stdlib/../../../../../newlib/libc/stdlib/mallocr.c:3340: more undefined references to `_sbrk_r' follow
collect2.exe: error: ld returned 1 exit status
C:/Users/Philippe/Eclipseworkspace/ESP8266_Relay_Board_1ch_16102018/Makefile:197: recipe for target 'build/app.out' failed
mingw32-make.exe: *** [build/app.out] Error 1
```
Made some (probably dirty) workaround:

```
	}else if (os_strcmp(mqtt_temp_topic,strTopic) == 0 ) {
		char * newStr;
		char newStr2[6];
		//Print MQTT topic and payload before manipulating the string
		os_printf("MQTT topic: %s, data: %s \r\n", strTopic, strData);

		//Remove dots or commas as SDK 1.3.0 doesn't like/support floats
		newStr = strtok (strData,",.");
		strcpy (newStr2,newStr);

		//debug lines
		//os_printf("Initial format MQTT data: %s \r\n", newStr);
		  while (newStr != NULL)
		  {
		    newStr = strtok (NULL, ",.");
				if (newStr==NULL) {
				//do nothing to avoid crash when tokens are null
				}
				else {
				strcat (newStr2,newStr);
				//debug lines
				//os_printf("While loop MQTT data: %s \r\n", newStr);
				}
		  }

		  	os_printf("New string after formatting payload: %s \r\n", newStr2);

		  	//Not working with SDK 1.3.0 MQTTreading=atof(strData)*100;
		  	//MQTTreading=atoi(strData)*100;
		  	MQTTreading=atoi(newStr2);
			os_printf("MQTT temp: %d \r\n", MQTTreading);

	}
	//os_printf("MQTT topic: %s, data: %s \r\n", strTopic, strData);
}
```
TCP: data received 46 bytes
MQTT strSubsTopic: heating/control/relay/e, strTopic: /ESP_Easy_Mega_3/HTU21D_3/Temperature 
MQTT topic: /ESP_Easy_Mega_3/HTU21D_3/Temperature, data: 20.77 
New string after formatting payload: 2077 
MQTT temp: 2077 

It works, so happy for now. Really curious if you Arduino port will work. That would be good to re-compile with the latest SDK / Arduino-ESP8266 releases.
